# Generated by Django 2.2.1 on 2019-05-22 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_value', models.IntegerField()),
                ('max_value', models.IntegerField()),
                ('hardware_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SensorHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('value', models.CharField(max_length=400)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_history', to='api.Sensor')),
            ],
        ),
    ]
